### PR TITLE
Added lab_report function with documentation and R Markdown templates…

### PR DESCRIPTION
**Pull request by ismayc**
… for Lab 1 and in general

### CODE REVIEW

**Comment by andrewpbray** [comment]
Looks like the build through travis failed, though I can't really parse the error code to figure out why. Looks like the error was on the initial R installation and didn't even get to your changes. Any ideas?

**Comment by ismayc** [comment]
I haven’t done anything with travis unfortunately and it does look like the error comes from just installing R.  

Chester

On Thu, Aug 04, 2016 at 1:53 PM Andrew Bray

<
mailto:Andrew Bray <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Looks like the build through travis failed, though I can't really parse the error code to figure out why. Looks like the error was on the initial R installation and didn't even get to your changes. Any ideas?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/andrewpbray/oilabs/pull/31#issuecomment-237648462
, or

**Comment by ismayc** [comment]
I looked into the error a bit and it might just be an internet connectivity issue:  
https://github.com/travis-ci/travis-ci/issues/6202
Chester

On Thu, Aug 04, 2016 at 1:57 PM Chester Ismay

<
mailto:Chester Ismay <ismay9@gmail.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I haven’t done anything with travis unfortunately and it does look like the error comes from just installing R.  

Chester

On Thu, Aug 04, 2016 at 1:53 PM Andrew Bray

<
mailto:Andrew Bray <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Looks like the build through travis failed, though I can't really parse the error code to figure out why. Looks like the error was on the initial R installation and didn't even get to your changes. Any ideas?

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/andrewpbray/oilabs/pull/31#issuecomment-237648462
, or

**Comment by andrewpbray** [comment]
Hmm, strange. I wonder if it will periodically try to re-run and fix itself. I'll check back later today and if it hasn't I'll go ahead and merge the request then we can go from there.

**Comment by andrewpbray** [comment]
Well, re-doing the build worked! Guess it was some issue on the travis side of things.

**Comment by ismayc** [comment]
Great!  I'm going to have to look into travis one of these days.

Chester




On Thu, Aug 4, 2016 at 7:11 PM -0700, "Andrew Bray" <notifications@github.com> wrote:












Merged #31.

**Pull request merged**
