### PR TITLE
Added RMarkdown template creation

### PR DESCRIPTION
**Pull request by ismayc**

### CODE REVIEW

**Comment by andrewpbray** [comment]
Hey Chester, do you remember what the story was w this pull request? Also: did you change accounts from chesterismay?

**Comment by ismayc** [comment]
This was the initial attempt for us to add templates to the package.  We decided to just go from my ismayc fork.  There are a bunch of other things I tweaked in that fork so I didn't want to kill it.  That's why I forked into the Reedies org and pr'ed from there.

Chester




On Thu, Aug 4, 2016 at 6:49 PM -0700, "Andrew Bray" <notifications@github.com> wrote:












Hey Chester, do you remember what the story was w this pull request? Also: did you change accounts from chesterismay?

**Comment by andrewpbray** [comment]
Gotcha. So ok if i close this?

**Comment by ismayc** [comment]
Sure!

Chester




On Thu, Aug 4, 2016 at 9:24 PM -0700, "Andrew Bray" <notifications@github.com> wrote:










Gotcha. So ok if i close this?



On Thu, Aug 4, 2016 at 7:50 PM, Chester Ismay <notifications@github.com>

wrote:



> This was the initial attempt for us to add templates to the package.  We

> decided to just go from my ismayc fork.  There are a bunch of other things

> I tweaked in that fork so I didn't want to kill it.  That's why I forked

> into the Reedies org and pr'ed from there.

>

> Chester

>

>

>

>

> On Thu, Aug 4, 2016 at 6:49 PM -0700, "Andrew Bray" <

**Pull request closed without merging**
